# Generated by Django 2.2.16 on 2022-05-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220528_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isliked',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': '  Пользователи'},
        ),
    ]
